[settings]
lockfile = true

[tools]
actionlint = "1.7.12"
editorconfig-checker = "3.7.0"
fnox = "1.27.1"
gitleaks = "8.30.1"
java = "temurin-21.0.11+10.0.LTS"
lefthook = "2.1.9"
terraform = "1.15.6"
tflint = "0.63.1"
zizmor = "1.26.1"
